import { A320Failure } from '../../../../../../../fbw-a32nx/src/systems/failures/src/a320';

const failureMap: { [key: string]: number } = {
    'FAC 1': A320Failure.Fac1Failure,
    'FAC 2': A320Failure.Fac2Failure,
    'TR 1': A320Failure.TransformerRectifier1,
    'TR 2': A320Failure.TransformerRectifier2,
    'ESS TR': A320Failure.TransformerRectifierEssential,
    'ELAC 1': A320Failure.Elac1Failure,
    'ELAC 2': A320Failure.Elac2Failure,
    'SEC 1': A320Failure.Sec1Failure,
    'SEC 2': A320Failure.Sec2Failure,
    'SEC 3': A320Failure.Sec3Failure,
    'FCDC 1': A320Failure.Fcdc1Failure,
    'FCDC 2': A320Failure.Fcdc2Failure,
    'Green reservoir leak': A320Failure.GreenReservoirLeak,
    'Blue reservoir leak': A320Failure.BlueReservoirLeak,
    'Yellow reservoir leak': A320Failure.YellowReservoirLeak,
    'Green reservoir air leak': A320Failure.GreenReservoirAirLeak,
    'Blue reservoir air leak': A320Failure.BlueReservoirAirLeak,
    'Yellow reservoir air leak': A320Failure.YellowReservoirAirLeak,
    'Green reservoir return leak': A320Failure.GreenReservoirReturnLeak,
    'Blue reservoir return leak': A320Failure.BlueReservoirReturnLeak,
    'Yellow reservoir return leak': A320Failure.YellowReservoirReturnLeak,
    'Green engine pump overheat': A320Failure.GreenEdpOverheat,
    'Blue electric pump overheat': A320Failure.BlueEpumpOverheat,
    'Yellow engine pump overheat': A320Failure.YellowEdpOverheat,
    'Yellow electric pump overheat': A320Failure.YellowEpumpOverheat,
    'Captain PFD display': A320Failure.LeftPfdDisplay,
    'F/O PFD display': A320Failure.RightPfdDisplay,
    'LGCIU 1 Power supply': A320Failure.LgciuPowerSupply1,
    'LGCIU 2 Power supply': A320Failure.LgciuPowerSupply2,
    'LGCIU 1 Internal error': A320Failure.LgciuInternalError1,
    'LGCIU 2 Internal error': A320Failure.LgciuInternalError2,
    'Proximity sensor damage uplock nose gear #1': A320Failure.GearProxSensorDamageGearUplockNose1,
    'Proximity sensor damage downlock nose gear #2': A320Failure.GearProxSensorDamageGearDownlockNose2,
    'Proximity sensor damage uplock right gear #1': A320Failure.GearProxSensorDamageGearUplockRight1,
    'Proximity sensor damage downlock right gear #2': A320Failure.GearProxSensorDamageGearDownlockRight2,
    'Proximity sensor damage uplock left gear #2': A320Failure.GearProxSensorDamageGearUplockLeft2,
    'Proximity sensor damage downlock left gear #1': A320Failure.GearProxSensorDamageGearDownlockLeft1,
    'Proximity sensor damage closed nose gear door #1': A320Failure.GearProxSensorDamageGearDoorClosedNose1,
    'Proximity sensor damage opened nose gear door #2': A320Failure.GearProxSensorDamageGearDoorOpenedNose,
    'Proximity sensor damage closed right gear door #1': A320Failure.GearProxSensorDamageGearDoorClosedRight1,
    'Proximity sensor damage opened right gear door #2': A320Failure.GearProxSensorDamageGearDoorOpenedRight2,
    'Proximity sensor damage closed left gear door #2': A320Failure.GearProxSensorDamageGearDoorClosedLeft2,
    'Proximity sensor damage opened left gear door #1': A320Failure.GearProxSensorDamageGearDoorOpenedLeft1,
    'Proximity sensor damage nose gear shock absorber compressed': A320Failure.GearProxSensorDamageGearShockAbsorberCompressedNose,
    'Proximity sensor damage right gear shock absorber compressed': A320Failure.GearProxSensorDamageGearShockAbsorberCompressedRight,
    'Proximity sensor damage left gear shock absorber compressed': A320Failure.GearProxSensorDamageGearShockAbsorberCompressedLeft,
    'Proximity sensor damage nose gear axle': A320Failure.GearProxSensorDamageGearAxleNose,
    'Proximity sensor damage right gear axle': A320Failure.GearProxSensorDamageGearAxleRight,
    'Proximity sensor damage left gear axle': A320Failure.GearProxSensorDamageGearAxleLeft,
};

export function getIdentifier(description: string): number | undefined {
    return failureMap[description];
}
